'use strict';
(() => {
 const E=ED,$=s=>document.querySelector(s),app=$('#app'),overlay=$('#overlay'),KEY='elementaldice-v2';
 const assetRoot=new URL('../Card/WebP/',document.currentScript.src);
 let state,storageOK=true,dockObserver;
 try{const saved=JSON.parse(localStorage.getItem(KEY));state=saved?.version===2?saved:E.initial();}catch{state=E.initial();storageOK=false;}
 E.migrateBalance(state);
 const ui={view:state.run?.scene||'home',selected:null,die:null,filter:'all',query:'',owned:true,draft:null,driving:false,fast:false,modal:null,drag:null};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const button=(text,act,extra='',cls='')=>`<button class="${cls}" data-act="${act}" ${extra}>${text}</button>`;
 const label={normal:'일반전',elite:'중간보스',boss:'최종 보스',town:'마을'};
 const symbols={normal:'⚔',elite:'✦',boss:'♜',town:'⌂'};
 const themes=['#578791','#648f9b','#bd9756','#5f8c75','#a87688','#ac7155','#978353','#ad9064','#598c78','#71648b','#845f83'];
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}}
 function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600);}
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ui.fast?0:ms));
 function elIcon(e){const a=E.elements[e];return `<span class="element" style="--e:${a.color}" title="${a.name}" aria-label="${a.name}">${a.glyph}</span>`;}
 function header(title='ElementalDice'){return `<header class="topbar"><span class="brand">${esc(title)}</span><div class="row">${button('⛶','fullscreen','aria-label="전체 화면"','quiet')}${button('?','help','aria-label="도움말"','quiet')}${button('☰','menu','aria-label="메뉴"','quiet')}</div></header>`;}
 function card(def,inst=null,{catalog=false,detail=false}={}){
  const r=state.run,selected=inst?.uid===ui.selected,a=inst?E.action(inst,inst.side==='p'?r.inventory:[],r.battle):null;
  const ready=inst?.side==='p'&&r.battle.phase==='p_attack'&&E.role(inst)==='attack'&&!inst.used&&a.valid;
  const selectedAttacker=inst?.side==='e'&&r?.battle.phase==='p_attack'?r.battle.players.find(c=>c.uid===ui.selected&&E.role(c)==='attack'&&!c.used&&E.action(c,r.inventory,r.battle).valid):null;
  const prediction=selectedAttacker&&!inst.dead?E.attackPreview(selectedAttacker,inst,r.inventory,r.battle):null;
  const placing=inst?.side==='p'&&!detail&&r.battle.phase==='p_place'&&!inst.dead;
  const hp=`<span class="card-hp" aria-label="체력 ${inst?.hp??def.hp}">♥ ${inst?.hp??def.hp}${inst?.guard?' ✦':''}</span><span class="card-mana" aria-label="비용 ${def.cost}">◇ ${def.cost}</span>`;
  return `<article style="--card-ratio:${def.width}/${def.height}" class="card ${inst?.dead?'dead':''} ${placing?'placing':''} ${selected?'selected':''} ${ready?'attack-ready':''}" role="button" tabindex="0" aria-label="${esc(def.name)}${inst?' '+(E.role(inst)==='attack'?'공격행':'방어행'):''}" data-act="${inst?'select':'detail'}" data-id="${inst?.uid||def.id}" data-card="${def.id}" ${inst?`data-instance="${inst.uid}" data-side="${inst.side}" data-drag="card"`:''}>
   ${inst?`<div class="card-art">`:""}${!inst?.dead?`<img class="card-image" draggable="false" data-image="${def.id}" width="${def.width}" height="${def.height}" alt="${esc(def.name)}" decoding="async"><span class="card-placeholder">${esc(def.title)}</span>`:''}
   ${inst?`</div><span class="battle-card-name">${esc(def.name)}</span>`:''}${hp}
   ${a?.valid||inst?.shield?`<span class="card-power">${E.role(inst)==='defense'?'⛨':'⚔'} ${inst.shield?.value??a.value}</span>`:''}
   ${placing?cardSlots(inst,def):inst?`<div class="mini-dice">${['L','R'].map(side=>`<div class="mini-dice-group">${Array.from({length:side==='L'?def.leftSlots:def.rightSlots},(_,i)=>{const d=inst[side][i];return d?`<span class="mini-die" role="img" aria-label="${E.elements[d.element].name} ${d.value}" style="--e:${E.elements[d.element].color}">${dieFace(d)}</span>`:'<span class="mini-die" style="visibility:hidden"></span>';}).join('')}</div>`).join('')}</div>`:''}

   <div class="card-bottom"><div class="row"><span>${Object.entries(def.dice).map(([e,n])=>elIcon(e)+n).join(' ')}</span><span class="card-defense" title="방어: ${E.elements[def.element].name}" aria-label="방어: ${E.elements[def.element].name}" style="--e:${E.elements[def.element].color}">${E.elements[def.element].glyph}</span></div></div><div class="card-desc">${esc(def.desc)}</div>${prediction?`<div class="damage-preview">예상 피해 ${prediction.damage}</div>`:''}
  </article>`;
 }
 // Images get a URL only after intersecting the viewport. Queued work is discarded on navigation.
 const imageCache=new Map(),loadedImages=new Map(),failures=new Set();let observer,imageQueue=[],activeImages=0,imageEpoch=0;
 function imageURL(id){const c=E.byId[id];const url=new URL(c.image.split('/').map(encodeURIComponent).join('/'),assetRoot);url.searchParams.set('v',c.version);return url.href;}
 function installImages(){observer?.disconnect();imageQueue=[];imageEpoch++;const epoch=imageEpoch;
  observer=new IntersectionObserver(entries=>{for(const entry of entries){const img=entry.target;if(!entry.isIntersecting)continue;observer.unobserve(img);imageQueue.push({img,id:img.dataset.image,epoch});}pumpImages();},{rootMargin:'0px',threshold:.01});
  document.querySelectorAll('img[data-image]').forEach(img=>{const known=loadedImages.get(img.dataset.image);if(known){img.src=known;img.closest('.card').classList.add('loaded');}else if(!img.getAttribute('src'))observer.observe(img);});
 }
 function pumpImages(){while(activeImages<4&&imageQueue.length){const task=imageQueue.shift();if(task.epoch!==imageEpoch||!task.img.isConnected)continue;
   const {img,id}=task;activeImages++;let promise=imageCache.get(id);
   if(!promise){promise=new Promise((resolve,reject)=>{const loader=new Image();loader.onload=()=>resolve(imageURL(id));loader.onerror=()=>reject(Error('image'));loader.src=imageURL(id);});imageCache.set(id,promise);}
   promise.then(url=>{loadedImages.set(id,url);if(img.isConnected){img.src=url;img.closest('.card').classList.add('loaded');}failures.delete(id);}).catch(()=>{imageCache.delete(id);failures.add(id);if(img.isConnected){const c=img.closest('.card');c.classList.add('failed');c.querySelector('.card-placeholder').innerHTML=esc(E.byId[id].title)+button('이미지 재시도','retry',`data-id="${id}"`,'image-retry');}}).finally(()=>{activeImages--;pumpImages();updateAction();});
  }}
 function visibleImageStatus(){return [...document.querySelectorAll('#app .card img[data-image]')].filter(img=>{const r=img.getBoundingClientRect();return r.bottom>58&&r.top<innerHeight&&r.right>0&&r.left<innerWidth;}).some(img=>!img.closest('.card').classList.contains('loaded'));}
 async function imagesReady(){while(ui.view==='battle'&&visibleImageStatus())await wait(90);}
 function home(){const owned=Object.values(state.collection).reduce((a,b)=>a+b,0);return header()+`<section class="hero"><div class="hero-art"><div class="sigil"></div><span class="rune">ᛟ</span></div><div class="eyebrow">A CHRONICLE OF ELEVEN MYTHS</div><h1>ElementalDice</h1><p>신화를 소환하고, 운명을 배치하세요.<br>다섯 원소와 주사위로 이어 가는 당신의 원정.</p><div class="hero-actions">${state.run?button('원정 이어하기 →','continue','','primary'):button('원정 시작 →','world','','primary')}${button('덱 구성','deck')}</div></section><div class="home-stats"><span><b>${owned}</b>보유 카드</span><span><b>11</b>신화권</span><span><b>${state.deck.length}</b>출전 덱</span></div>${!storageOK?'<p class="notice">이 브라우저에서는 자동 저장을 사용할 수 없습니다.</p>':''}`;}
 function worldMap(){return `<div class="world" aria-label="세계 지도"><svg viewBox="0 0 600 300" role="img"><title>신화권을 선택하는 세계 지도</title><g class="world-grid">${[60,120,180,240].map(y=>`<path d="M0 ${y}H600"/>`).join('')}${[100,200,300,400,500].map(x=>`<path d="M${x} 0V300"/>`).join('')}</g><g class="continents"><path d="M38 69l30-28 52-7 34 19 35-9 18 24-18 28-30 8-15 26-23 9-14-26-29-4-24-18z M121 133l32 7 25 33-13 53-20 38-15-27-3-44-15-28z M246 67l37-31 47 12 20 21 18 18-28 14-36-7-29 13-26-14z M267 112l49-10 40 25-7 40-26 40-22 13-23-45-20-35z M342 52l60-14 67 6 70 30 10 33-35 7-37-10-21 16-21 17-15 47-27-32-20-44-33-17z M455 209l43-12 42 25-11 23-48 3-31-21z"/></g>${[[277,52],[306,89],[310,126],[489,105],[515,108],[458,110],[407,148],[343,112],[116,136],[150,82],[258,84]].map(([x,y],i)=>`<circle class="world-dot" cx="${x}" cy="${y}" r="3"><title>${E.data.cultures[i]}</title></circle>`).join('')}</svg></div>`;}
 function world(){return header()+`<main class="content"><div class="section-heading"><div><div class="eyebrow">WORLD ATLAS</div><h2>어디로 떠날까요?</h2></div>${button('뒤로','home','','quiet')}</div>${worldMap()}<div class="culture-grid">${E.data.cultures.map((c,i)=>button(`${esc(c)}<small>20종의 신화 · 11개의 여정</small>`,'culture',`data-index="${i}"`)).join('')}</div><p class="muted" style="margin-top:18px;font-size:12px">편성한 ${state.deck.length}장으로 출발합니다. 맵 입장 시 아티펙트 1개를 받습니다.</p></main>`;}
 function resourceLine(){const r=state.run;return `<div class="row between" style="margin-top:12px"><span>사용 가능 ${E.availableCards(r).length}/${r.roster.length}장</span><span style="color:#8ad7ed">◇ ${r.mana}/${r.maxMana}</span><span class="gold">${r.gold} G</span></div>`;}
 function map(){const r=state.run;return header()+`<main class="theme-field" style="--theme:${themes[E.data.cultures.indexOf(r.culture)]}"><div class="content"><div class="eyebrow">EXPEDITION ${String(r.node+1).padStart(2,'0')} / 11</div><h2>${esc(r.culture)}의 길</h2>${resourceLine()}<small>아래에서 위로, 신화의 중심을 향해.</small></div><div class="route">${r.stages.map((s,i)=>`<button class="node ${i===r.node?'current':''} ${i<r.node?'done':''}" data-act="enter" ${i!==r.node?'disabled':''}><span class="node-icon">${i<r.node?'✓':symbols[s.kind]}</span><span><b>${String(i+1).padStart(2,'0')} · ${label[s.kind]}</b><small>${i<r.node?'지나온 길':i===r.node?'이곳으로 이동 →':'아직 닿지 않은 곳'}</small></span></button>`).join('')}</div></main>`;}
 function catalog(){const counts={};ui.draft.forEach(id=>counts[id]=(counts[id]||0)+1);const shown=E.cards.filter(c=>(!ui.owned||state.collection[c.id])&&(ui.filter==='all'||c.culture===ui.filter)&&(!ui.query||(c.name+' '+c.title).toLowerCase().includes(ui.query.toLowerCase())));
  return header()+`<main class="content"><div class="section-heading"><div><div class="eyebrow">YOUR COLLECTION</div><h2>덱 구성</h2></div>${button('돌아가기','home','','quiet')}</div><small>원정 전에 편성하세요. 최소 10장 · 보유 사본 수 이내</small><div class="catalog-tools"><input type="search" id="card-search" placeholder="카드 이름 검색" value="${esc(ui.query)}" aria-label="카드 이름 검색"><select id="culture-filter" aria-label="신화권 필터"><option value="all">모든 신화권</option>${E.data.cultures.map(c=>`<option ${ui.filter===c?'selected':''}>${esc(c)}</option>`).join('')}</select>${button(ui.owned?'보유 카드만':'전체 카드','toggle-owned')}</div><div class="catalog">${shown.map(c=>`<div class="catalog-entry">${card(c,null,{catalog:true})}<div class="deck-controls">${button('−','deck-remove',`data-id="${c.id}" ${!counts[c.id]?'disabled':''} aria-label="${esc(c.name)} 덱에서 빼기"`)}<small>${counts[c.id]||0} / ${state.collection[c.id]||0}</small>${button('+','deck-add',`data-id="${c.id}" ${(counts[c.id]||0)>=(state.collection[c.id]||0)?'disabled':''} aria-label="${esc(c.name)} 덱에 넣기"`)}</div></div>`).join('')}</div>${!shown.length?'<p class="empty-message">조건에 맞는 카드가 없습니다.</p>':''}<div class="deck-summary"><span>편성 <b class="gold">${ui.draft.length}</b>장</span>${button('덱 저장','deck-save',`${ui.draft.length<10||state.run?'disabled':''}`,'primary')}</div>${state.run?'<p class="notice">원정 중에는 덱을 변경할 수 없습니다.</p>':''}</main>`;
 }
 function board(side){const b=state.run.battle,cs=side==='e'?b.enemies:b.players,rows=side==='e'?[1,0]:[0,1];return `<div class="board ${side==='e'?'enemy-board':`player-board ${b.phase==='p_place'?'placing-board':''}`}">${rows.map(row=>`<div class="board-row-label"><span>${row?'후열 · 공격':'전열 · 방어'}</span><span>${side==='e'?'적':'플레이어'}</span></div>${[0,1,2].map(col=>{const pos=row*3+col,c=cs.find(c=>c.pos===pos&&!c.dead);return `<div class="field-cell" style="--card-ratio:${c?E.byId[c.id].width:384}/${c?E.byId[c.id].height:533}" data-position="${pos}" data-field-side="${side}">${c?card(E.byId[c.id],c):`<button class="empty-cell" ${side==='p'?`data-act="move" data-position="${pos}" aria-label="${pos<3?'방어':'공격'} ${pos%3+1}로 이동"`:'disabled'}>${side==='p'?'이동 가능':'빈 자리'}</button>`}</div>`;}).join('')}`).join('')}</div>`;}
 function dieFace(d){const positions=[[],[4],[0,8],[0,4,8],[0,2,6,8],[0,2,4,6,8],[0,2,3,5,6,8]][d.value];return `<span class="die-face" aria-hidden="true">${positions.map(pos=>`<i class="die-pip" style="grid-row:${Math.floor(pos/3)+1};grid-column:${pos%3+1}">${E.elements[d.element].glyph}</i>`).join('')}</span>`;}
 function die(d,interactive=true){return `<button class="die ${ui.die===d.uid?'selected':''}" style="--e:${E.elements[d.element].color}" data-act="die" data-id="${d.uid}" data-drag="die" title="${E.elements[d.element].name} ${d.value}" aria-label="${E.elements[d.element].name} 주사위 ${d.value}" ${!interactive?'disabled':''}>${dieFace(d)}</button>`;}
 const phaseNames={p_prep:'내 턴 · 준비',p_roll:'주사위 굴리는 중',p_place:'내 턴 · 주사위 배치',p_attack:'내 턴 · 공격',e_roll:'적의 주사위 굴림',e_place:'적의 방어·공격 배치',e_attack:'적의 공격'};
 function diceZone(){const b=state.run.battle,rolling=['p_roll','e_roll'].includes(b.phase),ds=rolling?b.rollDisplay:b.phase.startsWith('e')?b.ePool:b.pPool;return `<section class="dice-zone ${rolling?'rolling':''}" aria-label="중앙 주사위 굴림판"><div class="dice-head"><span>${rolling?'ROLLING DICE':'DICE POOL · 1 → 6'}</span><span>${ds.length}개</span></div><div class="dice-pool">${(rolling?ds:E.sorted(ds)).map(d=>die(d,b.phase==='p_place')).join('')}</div>${!ds.length?`<p class="dice-hint">${b.phase==='p_prep'?'카드가 준비되었습니다. 주사위를 굴리세요.':b.phase==='p_attack'?'빛나는 후열 카드를 상대에게 드래그하세요.':'주사위가 카드 위에 배치되었습니다.'}</p>`:''}</section>`;}
 function cardSlots(c,def){return `<div class="card-slots" aria-label="${esc(def.name)} 주사위 배치">${['L','R'].map(side=>`<div class="card-slot-column">${Array.from({length:side==='L'?def.leftSlots:def.rightSlots},(_,i)=>{const d=c[side][i];return `<button class="slot" data-act="slot" data-id="${c.uid}" data-slot-side="${side}" data-slot-index="${i}" aria-label="${esc(def.name)} ${side==='L'?'왼쪽':'오른쪽'} ${i+1}${d?` ${E.elements[d.element].name} ${d.value} 주사위 회수`:' 배치'}">${d?`<span class="die" style="--e:${E.elements[d.element].color}">${dieFace(d)}</span>`:'+'}</button>`;}).join('')}</div>`).join('')}</div>`;}
 function selection(){const r=state.run,b=r.battle;return `<section class="selection-panel"><h2>출전 카드 선택</h2><p>상대 카드를 확인하고 비용 합계 ${r.maxMana} 이내로 선택하세요. 이번 스테이지 동안 함께합니다.</p><small>선택 ${b.selection.length}/6장 · 남은 마나 ${r.mana} · 쓰러진 카드 ${r.roster.filter(c=>c.fallen).length}장</small><div class="catalog">${r.roster.map(entry=>{const chosen=b.selection.includes(entry.uid),def=E.byId[entry.id];return `<div class="catalog-entry ${chosen?'chosen':''} ${entry.fallen?'fallen':''}">${card(def)}${button(entry.fallen?'이번 맵 사용 불가':chosen?'✓ 선택 해제':`선택 · ◇ ${def.cost}`,'choose-card',`data-id="${entry.uid}" ${entry.fallen||!chosen&&(def.cost>r.mana||b.selection.length>=6)?'disabled':''}`,'full')}</div>`;}).join('')}</div></section>`;}
 function footer(){const r=state.run,b=r.battle;const text=b.phase==='p_select'?'출전 확정':b.phase==='p_prep'?'주사위 굴리기':b.phase==='p_place'?'배분 확정 → 공격':b.phase==='p_attack'?'턴 종료':'진행 중…';const act=b.phase==='p_select'?'deploy':b.phase==='p_prep'?'roll':b.phase==='p_place'?'confirm':'end-turn';return `<div class="battle-dock">${b.phase==='p_select'?'':diceZone()}<footer class="battle-footer"><div class="resources"><div class="mana-gems" aria-label="마나 ${r.mana}/${r.maxMana}">${[0,1].map(row=>`<span class="gem-row">${Array.from({length:5},(_,i)=>`<i class="${row*5+i>=r.maxMana?'locked':row*5+i>=r.mana?'spent':''}"></i>`).join('')}</span>`).join('')}</div><small>${r.mana}/${r.maxMana}</small></div><div class="inventory">${r.inventory.map((it,i)=>button(it?(E.items[it.id].artifact?'✧':it.id==='potion'?'♥':it.id==='mana'?'◇':'✦')+`<small>${it.count}</small>`:'·','item',`data-index="${i}" aria-label="${it?E.items[it.id].name:'빈 아이템 슬롯'}" ${!it?'disabled':''}`)).join('')}</div>${button(text,act,'id="primary-action"','primary')}</footer></div>`;}
 function battle(){const r=state.run,b=r.battle;return header()+`<main class="battle theme-field" style="--theme:${themes[E.data.cultures.indexOf(r.culture)]}"><div class="row between battle-title"><span class="eyebrow">${esc(r.culture)} · ${r.node+1}/11</span><small>${label[b.kind]} · TURN ${Math.max(1,b.round)}</small></div>${board('e')}${b.phase==='p_select'?selection():board('p')}${footer()}</main>`;}
 function reward(){const r=state.run,q=r.reward;return header()+`<main class="content"><div class="reward-banner"><div class="eyebrow">VICTORY</div><h2>${q.kind==='boss'?'신화의 끝에 도달했습니다':'길이 열렸습니다'}</h2><p class="gold" style="margin-top:12px">${q.kind==='boss'?'카드가 컬렉션에 추가되었습니다.':`+ ${q.gold} G`}</p></div>${q.card?`<div class="reward-card">${card(E.byId[q.card])}</div><p style="text-align:center">${esc(E.byId[q.card].name)}</p>`:''}${q.kind==='normal'?`<p class="muted" style="text-align:center;margin:15px">카드와 마나보석 중 하나를 선택하세요.</p><div class="choice-grid">${button(q.choice==='card'?'카드 획득 완료':'카드 받기','reward-card',`${q.choice?'disabled':''}`,'primary')}${button(q.choice==='mana'?'마나보석 획득 완료':`마나보석 +1${r.maxMana>=10?' · 최대':''}`,'reward-mana',`${q.choice||r.maxMana>=10?'disabled':''}`)}</div>`:''}${q.items.map((it,i)=>`<div class="item-row"><div><b>${E.items[it.id].name}</b><small>${E.items[it.id].desc}</small></div>${it.status==='pending'?button('받기','reward-item',`data-index="${i}"`):`<small>${it.status==='received'?'수령 완료':'받지 않음'}</small>`}</div>`).join('')}<div style="margin-top:25px">${button(q.kind==='boss'?'원정 마치기':'다음 길로 →','reward-next',`${q.choice===null||q.items.some(it=>it.status==='pending')?'disabled':''}`,'primary full')}</div></main>`;}
 function town(){const r=state.run,t=r.towns[r.node];return header()+`<main class="content"><div class="eyebrow">A MOMENT OF REST</div><h2>${esc(r.culture)}의 마을</h2>${resourceLine()}<div class="town-art">⌂</div><p class="notice">${esc(t.event)}</p>${t.pending?button('선물 받기 / 정리','town-gift','','full'):''}${Object.entries(t.stock).map(([id,n])=>`<div class="item-row"><div><b>${E.items[id].name}</b><small>${E.items[id].desc} · 재고 ${n}</small></div>${button(`${E.items[id].buy} G`,'buy',`data-id="${id}" ${!n||r.gold<E.items[id].buy?'disabled':''}`)}</div>`).join('')}<h3 style="margin:20px 0 8px">가방 · 판매</h3>${r.inventory.map((s,i)=>s?`<div class="item-row"><div><b>${E.items[s.id].name} ×${s.count}</b><small>${E.items[s.id].desc}</small></div>${button(`${E.items[s.id].sell} G 판매`,'sell',`data-index="${i}"`)}</div>`:'').join('')}${button('다음 길로 →','leave-town',`${t.pending?'disabled':''}`,'primary full')}</main>`;}
 function result(){const q=state.result;return header()+`<main class="content"><div class="hero-art"><div class="sigil"></div><span class="rune">${q?.status==='cleared'?'✦':'◇'}</span></div><div class="reward-banner"><div class="eyebrow">EXPEDITION COMPLETE</div><h2>${q?.status==='cleared'?'원정 성공':q?.status==='abandoned'?'다음 여정을 기다리며':'원정 종료'}</h2><p class="muted" style="margin-top:15px">${esc(q?.culture)} · ${q?.wins||0}회 승리<br>획득한 카드는 컬렉션에 남습니다.</p></div>${button('메인 화면','home','','primary full')}</main>`;}
 function render(){const oldY=scrollY;dockObserver?.disconnect();app.innerHTML=({home,world,map,deck:catalog,battle,reward,town,result}[ui.view]||home)();installImages();const dock=$('.battle-dock');if(dock){dockObserver=new ResizeObserver(()=>document.documentElement.style.setProperty('--battle-dock-height',dock.getBoundingClientRect().height+'px'));dockObserver.observe(dock);}requestAnimationFrame(()=>scrollTo(0,oldY));updateAction();}
 function updateAction(){const btn=$('#primary-action');if(!btn)return;const b=state.run?.battle;if(!b)return;const loading=visibleImageStatus();btn.disabled=ui.attacking||loading||!['p_select','p_prep','p_place','p_attack'].includes(b.phase)||(b.phase==='p_select'&&!b.selection.length);btn.title=loading?'카드 이미지 로딩 중…':'';}
 function view(name){ui.view=name;ui.selected=null;ui.die=null;scrollTo(0,0);render();}
 function changed(){save();render();}
 function closeModal(){overlay.innerHTML='';ui.modal=null;installImages();}
 function modal(title,body,buttons=button('닫기','close-modal','','primary')){ui.modal=title;overlay.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><h2>${esc(title)}</h2>${body}<div class="buttons">${buttons}</div></section></div>`;installImages();overlay.querySelector('button')?.focus();}
 function details(id){const b=state.run?.battle,c=b?[...b.players,...b.enemies].find(c=>c.uid===id):null,def=E.byId[c?.id||id];if(!def)return;modal(def.name,`<div class="detail-card">${card(def,null,{detail:true})}</div><div class="detail-grid"><span>${esc(def.culture)} · ${def.rarity}</span><span>기본 체력 ${def.hp}</span><span>마나 비용 ${def.cost}</span><span>공급 ${def.supply}개</span><span>방어 ${E.elements[def.element].name}</span><span>공격 ${def.attacks.map(e=>E.elements[e].name).join(' / ')}</span></div><p>${esc(def.desc)}</p><small>보유 ${state.collection[def.id]||0}장 · ${def.tier==='정예'?'엘리트':def.tier} · 굴림 상한 ${def.maxRollDice}개 (왼쪽 ${def.leftSlots} / 오른쪽 ${def.rightSlots})</small>`);}
 function checkEnd(){if(!state.run)return true;const r=state.run;if(E.lost(r)){E.endRun(state,'defeated');save();view('result');return true;}if(E.won(r)){E.victory(state);save();view('reward');return true;}return false;}
 async function animateHit(hit){if(!hit||ui.fast)return;const source=document.querySelector(`[data-instance="${hit.from}"]`),target=document.querySelector(`[data-instance="${hit.to}"]`);if(!source||!target)return;target.scrollIntoView({block:'center',behavior:'instant'});await new Promise(requestAnimationFrame);
  const a=source.getBoundingClientRect(),z=target.getBoundingClientRect(),element=E.elements[hit.element],fx=document.createElement('span');fx.className=`attack-projectile projectile-${hit.element}`;fx.textContent=element.glyph;fx.style.cssText=`left:${a.left+a.width/2}px;top:${Math.max(65,Math.min(innerHeight-180,a.top+a.height/2))}px;--e:${element.color}`;document.body.append(fx);
  const startY=parseFloat(fx.style.top),endY=Math.max(65,Math.min(innerHeight-180,z.top+z.height/2));
  try{await fx.animate([{transform:'translate(-50%,-50%) scale(.5)',opacity:0},{transform:'translate(-50%,-50%) scale(1.2)',opacity:1,offset:.2},{transform:`translate(calc(-50% + ${z.left+z.width/2-a.left-a.width/2}px),calc(-50% + ${endY-startY}px)) scale(.8)`,opacity:1}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?80:480,easing:'ease-in'}).finished;
   await target.animate([{filter:`drop-shadow(0 0 12px ${element.color})`,transform:'translateX(-4px)'},{transform:'translateX(4px)',offset:.4},{filter:'none',transform:'translateX(0)'}],{duration:180}).finished;
  }catch{}finally{fx.remove();}
  const pop=document.createElement('span');pop.className='damage-pop';pop.textContent=hit.damage?`−${hit.damage}`:'방어';pop.style.left=z.left+z.width/2+'px';pop.style.top=endY+'px';document.body.append(pop);setTimeout(()=>pop.remove(),800);
 }
 async function attack(from,to){const r=state.run;if(!r||ui.attacking||visibleImageStatus())return;const hit=E.playerAttack(r,from,to);if(!hit)return;ui.attacking=true;updateAction();ui.selected=null;save();await animateHit(hit);ui.attacking=false;if(state.run!==r)return;if(checkEnd())return;render();}
 async function animateRoll(){const dice=[...document.querySelectorAll('.dice-zone .die')];if(ui.fast)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;await Promise.all(dice.map((el,i)=>{if(!el.animate)return wait(400);const x=(i%3-1)*100,y=-(40+(i%5)*12);return el.animate([{transform:`translate(${x}px,${y}px) rotate(${i%2?'-':''}180deg) scale(.6)`,opacity:0},{transform:`translate(${x*.4}px,30px) rotate(${i%2?'-':''}280deg) scale(1)`,opacity:1,offset:.45},{transform:'translate(0,-10px) rotate(350deg)',offset:.73},{transform:'translate(0,0) rotate(360deg)',opacity:1}],{duration:reduced?80:950,delay:reduced?0:(i%5)*45,easing:'ease-out',fill:'backwards'}).finished.catch(()=>{});}));}
 async function animateEnemyPlacement(plan){if(!plan||ui.fast||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const target=document.querySelector(`[data-instance="${plan.uid}"]`);if(!target)return;const end=target.getBoundingClientRect();await Promise.all([...plan.L,...plan.R].map((d,i)=>{const source=document.querySelector(`.dice-pool [data-id="${d.uid}"]`);if(!source)return;const start=source.getBoundingClientRect(),ghost=source.cloneNode(true);ghost.style.cssText+=`;position:fixed;left:${start.left}px;top:${start.top}px;z-index:60;pointer-events:none`;document.body.append(ghost);return ghost.animate([{transform:'translate(0,0)'},{transform:`translate(${end.left+end.width/2-start.left}px,${end.top+end.height*.6-start.top}px) scale(.45)`}],{duration:400,delay:i*25,easing:'ease-in-out'}).finished.catch(()=>{}).finally(()=>ghost.remove());}));}
 async function drive(){if(ui.driving||ui.view!=='battle')return;ui.driving=true;const runId=state.run?.uid;let failed=false;
  try{while(state.run?.uid===runId&&ui.view==='battle'){const r=state.run,b=r.battle;if(!b)break;await imagesReady();if(ui.view!=='battle'||state.run?.uid!==runId)break;
   if(b.phase==='e_roll'||b.phase==='p_roll'){await animateRoll();if(ui.view!=='battle'||state.run?.uid!==runId)break;if(b.phase==='p_roll'){E.finishPlayerRoll(r);changed();break;}E.planEnemy(r);changed();await wait(450);}
   else if(b.phase==='e_place'){await animateEnemyPlacement(b.plan[b.planIndex]);if(ui.view!=='battle'||state.run?.uid!==runId)break;E.enemyPlacementStep(r);changed();await wait(300);}
   else if(b.phase==='e_attack'){if(b.queueIndex<b.queue.length){const hit=E.enemyAttackStep(r);save();await animateHit(hit);if(checkEnd())break;render();await wait(550);}else{E.preparePlayer(r);ui.selected=r.battle.players.find(c=>!c.dead)?.uid;changed();break;}}
   else break;
  }}catch(err){failed=true;console.error(err);toast('전투 처리를 잠시 멈췄습니다. 저장된 원정으로 다시 진입해 주세요.');}finally{ui.driving=false;if(!failed&&ui.view==='battle'&&['e_roll','e_place','e_attack','p_roll'].includes(state.run?.battle?.phase))setTimeout(drive,0);}
 }
 function replaceDialog(id,source,index){modal('가방에 넣을 공간 선택',`<p>${E.items[id].name}을 받을 공간이 없습니다. 교체할 슬롯의 기존 아이템은 모두 사라집니다.</p><div class="stack" style="margin-top:15px">${state.run.inventory.map((s,i)=>button(`${i+1}. ${s?E.items[s.id].name+' ×'+s.count:'빈 슬롯'}`,'replace-pending',`data-source="${source}" data-index="${index}" data-slot="${i}"`)).join('')}</div>`,button('받지 않기','skip-pending',`data-source="${source}" data-index="${index}"`));}
 const actions={
  'choose-card'(el){if(E.toggleCard(state.run,el.dataset.id))changed();},
  deploy(){if(E.deploy(state.run)){scrollTo(0,0);changed();drive();}},
  home(){closeModal();view('home');},world(){if(state.deck.length<10)return toast('덱을 10장 이상 편성해 주세요.');view('world');},continue(){view(state.run.scene);drive();},
  culture(el){E.newRun(state,E.data.cultures[+el.dataset.index]);save();view('map');},
  deck(){ui.draft=[...state.deck];view('deck');},'toggle-owned'(){ui.owned=!ui.owned;render();},
  'deck-add'(el){const id=el.dataset.id;if(ui.draft.filter(x=>x===id).length<(state.collection[id]||0)&&!state.run){ui.draft.push(id);render();}},
  'deck-remove'(el){const i=ui.draft.indexOf(el.dataset.id);if(i>=0&&!state.run){ui.draft.splice(i,1);render();}},
  'deck-save'(){if(ui.draft.length<10||state.run)return;state.deck=[...ui.draft];save();toast('출전 덱을 저장했습니다.');view('home');},
  enter(){const r=state.run;if(r.stages[r.node].kind==='town'){E.enterTown(r);save();view('town');}else{E.startBattle(r);r.scene='battle';save();view('battle');drive();}},
  'back-map'(){state.run.scene='map';save();view('map');},
  select(el){const b=state.run?.battle;if(!b||ui.view!=='battle')return;const c=[...b.players,...b.enemies].find(c=>c.uid===el.dataset.id);if(!c||c.dead)return;
   if(c.side==='e'){if(b.phase==='p_attack'&&ui.selected)attack(ui.selected,c.uid);else details(c.uid);}else{if(ui.die&&b.phase==='p_place'){const rect=el.getBoundingClientRect();if(E.placeDie(b,ui.die,c.uid,(ui.clickX??rect.left)<rect.left+rect.width/2?'L':'R'))ui.die=null;}ui.selected=c.uid;changed();}},
  detail(el){details(el.dataset.id);},die(el){if(state.run?.battle.phase==='p_place'){ui.die=el.dataset.id;render();}},
  slot(el){const b=state.run?.battle;if(!b)return;const c=b.players.find(c=>c.uid===el.dataset.id),side=el.dataset.slotSide,index=+el.dataset.slotIndex;if(!c)return;ui.selected=c.uid;
   if(c[side][index])E.removeDie(b,c.uid,side,index);else if(ui.die){if(!E.placeDie(b,ui.die,c.uid,side))return toast('등급별 좌우 칸 수를 확인하세요. 오른쪽은 같은 눈만 놓을 수 있습니다.');ui.die=null;}changed();},
  move(el){if(E.moveCard(state.run.battle,ui.selected,+el.dataset.position))changed();},
  roll(){if(visibleImageStatus())return;if(E.rollPlayer(state.run)){changed();drive();}},confirm(){if(visibleImageStatus())return;if(E.confirm(state.run)){ui.selected=null;changed();}},
  'end-turn'(){const positions=new Map([...document.querySelectorAll('[data-side="e"]')].map(el=>[el.dataset.instance,el.getBoundingClientRect()]));if(E.beginEnemy(state.run)){ui.selected=null;ui.die=null;changed();if(!ui.fast&&!matchMedia('(prefers-reduced-motion: reduce)').matches)document.querySelectorAll('[data-side="e"]').forEach(el=>{const old=positions.get(el.dataset.instance),now=el.getBoundingClientRect();if(old)el.animate([{transform:`translate(${old.left-now.left}px,${old.top-now.top}px)`},{transform:'translate(0,0)'}],{duration:450,easing:'ease-in-out'});});drive();}},
  'reward-card'(){if(E.chooseReward(state,'card'))changed();},'reward-mana'(){if(E.chooseReward(state,'mana'))changed();},
  'reward-item'(el){const i=+el.dataset.index;if(E.resolveRewardItem(state.run,i))changed();else replaceDialog(state.run.reward.items[i].id,'reward',i);},
  'replace-pending'(el){const source=el.dataset.source,i=+el.dataset.index,slot=+el.dataset.slot;modal('아이템 교체',`<p>${slot+1}번 슬롯의 아이템 전체를 버리고 교체할까요?</p>`,button('취소','close-modal')+button('교체','replace-confirm',`data-source="${source}" data-index="${i}" data-slot="${slot}"`,'primary'));},
  'replace-confirm'(el){const r=state.run;if(el.dataset.source==='reward')E.resolveRewardItem(r,+el.dataset.index,+el.dataset.slot);else{r.inventory[+el.dataset.slot]={id:r.towns[r.node].pending,count:1};r.towns[r.node].pending=null;}closeModal();changed();},
  'skip-pending'(el){if(el.dataset.source==='reward')E.resolveRewardItem(state.run,+el.dataset.index,'skip');else state.run.towns[state.run.node].pending=null;closeModal();changed();},
  'reward-next'(){if(E.rewardNext(state)){save();view(state.run?'map':'result');}},
  'town-gift'(){const r=state.run,t=r.towns[r.node];if(t.pending&&E.addItem(r,t.pending)){t.pending=null;changed();}else if(t.pending)replaceDialog(t.pending,'town',0);},
  buy(el){if(E.buy(state.run,el.dataset.id))changed();else toast('골드·재고 또는 가방 공간을 확인해 주세요.');},
  sell(el){if(E.sell(state.run,+el.dataset.index))changed();},
  'leave-town'(){const r=state.run;if(r.towns[r.node].pending)return;r.node++;r.scene='map';save();view('map');},
  item(el){const i=+el.dataset.index,s=state.run.inventory[i];if(!s)return;const it=E.items[s.id];modal(it.name,`<p>${it.desc}</p><small>보유 ${s.count}개${it.artifact?' · 보유 중 자동 적용, 같은 종류 효과 중첩 없음':''}</small>`,button('닫기','close-modal')+(!it.artifact?button('사용','use-item',`data-index="${i}" ${!['p_select','p_prep','p_place'].includes(state.run.battle?.phase)?'disabled':''}`,'primary'):''));},
  'use-item'(el){if(E.useItem(state.run,+el.dataset.index,ui.selected)){closeModal();changed();}else toast('회복·보호할 생존 카드를 먼저 선택하거나 사용 조건을 확인하세요.');},
  retry(el){failures.delete(el.dataset.id);imageCache.delete(el.dataset.id);const c=el.closest('.card');c?.classList.remove('failed');if(c){c.querySelector('.card-placeholder').textContent=E.byId[el.dataset.id].title;const img=c.querySelector('img');img.removeAttribute('src');observer.observe(img);}else installImages();},
  'exit-game'(){
   save();
   const raw=new URLSearchParams(location.search).get('returnTo');
   if(raw){try{const url=new URL(raw);if(url.protocol==='https:'&&!url.username&&!url.password&&[location.origin,'https://rudoloot.github.io'].includes(url.origin)){location.replace(url.href);return;}}catch{}}
   closeModal();view('home');
  },
  'close-modal':closeModal,
  log(){modal('전투 기록',(state.run?.battle.log||[]).slice().reverse().map(l=>`<p class="log-line">${esc(l)}</p>`).join('')||'<p>아직 공격 기록이 없습니다.</p>');},
  menu(){modal('ElementalDice',`<div class="stack">${button('메인 화면','home')}${button('게임 종료하기','exit-game')}${state.run?button('원정 포기','abandon-ask','','danger'):''}<small>진행 상황은 자동 저장됩니다.${!storageOK?' 현재 브라우저에서는 저장을 사용할 수 없습니다.':''}</small></div>`);},
  'abandon-ask'(){modal('원정을 마칠까요?','<p>획득한 카드와 덱 편성은 남고, 이번 맵의 골드·아이템·마나는 사라집니다.</p>',button('돌아가기','close-modal')+button('원정 포기','abandon','','danger'));},
  abandon(){E.endRun(state,'abandoned');closeModal();save();view('result');},
  async fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('이 브라우저에서는 전체 화면을 지원하지 않습니다.');}},
  help(){modal('주사위로 만드는 전투',`<div class="stack"><p>전투 시작 시 상대 카드를 보고 마나 한도 내에서 출전 카드를 선택합니다. 선택한 카드는 스테이지 동안 유지됩니다. 각 카드에 체력이 있고 상대 전멸 시 승리, 아군 전멸 시 패배합니다. 쓰러진 카드 사본은 이번 맵에서 다시 사용할 수 없습니다. 살아남은 카드는 다음 스테이지에서 체력이 회복됩니다. 앞줄은 방어, 뒷줄은 공격입니다.</p><p>주사위를 굴린 뒤 하단의 주사위를 카드 위 좌우 영역으로 드래그하거나, 주사위를 선택한 뒤 카드 칸을 누르세요. 놓인 주사위를 누르면 회수합니다. 왼쪽 슬롯은 합, 오른쪽은 같은 눈의 개수로 배율을 만듭니다.<br><b class="gold">왼쪽 3·5, 오른쪽 2·2 → (3+5)×2 = 16</b></p><p>배치 중 카드는 드래그하거나 카드 선택 후 빈 전장 칸을 눌러 이동합니다. 배분 확정 후 빛나는 후열 카드를 상대 카드로 드래그하거나 차례로 터치해 공격하세요. 방어를 넘긴 수치는 즉시 체력 피해가 됩니다.</p><p>불 → 나무 → 땅 → 바람 → 물 → 불<br>유리한 공격은 1.5배, 반대는 0.5배. 여러 원소를 섞거나 카드가 사용할 수 없는 속성이면 무속성 행동이 됩니다.</p><p>첫 적 턴은 전열에만 주사위를 배치합니다. 보스는 후열 중앙에 고정됩니다. 방어는 다음 상대 턴까지 유지합니다.</p></div>`);}
 };
 let suppressClick=false;
 document.addEventListener('click',event=>{ui.clickX=event.clientX;if(ui.attacking)return;if(suppressClick){event.preventDefault();return;}const el=event.target.closest('[data-act]');if(!el||el.disabled)return;const f=actions[el.dataset.act];if(f){event.preventDefault();try{f(el);}catch(error){console.error(error);toast(error.message);}}});
 document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();if((event.key==='Enter'||event.key===' ')&&event.target.matches('.card')){event.preventDefault();actions[event.target.dataset.act]?.(event.target);}});
 document.addEventListener('change',event=>{if(event.target.id==='culture-filter'){ui.filter=event.target.value;render();}});
 document.addEventListener('input',event=>{if(event.target.id==='card-search'){ui.query=event.target.value;clearTimeout(ui.searchTimer);ui.searchTimer=setTimeout(()=>{const pos=ui.query.length;render();const input=$('#card-search');input?.focus();input?.setSelectionRange?.(pos,pos);},180);}});
 document.addEventListener('pointerdown',event=>{const source=event.target.closest('[data-drag]');if(ui.attacking||!source||event.target.closest('.slot')||ui.modal||!state.run?.battle)return;const b=state.run.battle;if(source.dataset.drag==='die'&&b.phase!=='p_place'||source.dataset.drag==='card'&&source.dataset.side!=='p')return;ui.drag={source,type:source.dataset.drag,id:source.dataset.id,x:event.clientX,y:event.clientY,moved:false,pointer:event.pointerId};});
 function dragScroll(){const d=ui.drag;if(!d?.moved)return;const amount=d.lastY<100?-12:d.lastY>innerHeight-145?12:0;if(amount)scrollBy(0,amount);requestAnimationFrame(dragScroll);}
 document.addEventListener('pointermove',event=>{const d=ui.drag;if(!d)return;d.lastY=event.clientY;if(Math.hypot(event.clientX-d.x,event.clientY-d.y)>9&&!d.moved){d.moved=true;d.ghost=document.createElement('div');d.ghost.className='drag-ghost';d.ghost.textContent=d.type==='die'?'주사위':E.byId[state.run.battle.players.find(c=>c.uid===d.id)?.id]?.name||'카드';document.body.append(d.ghost);requestAnimationFrame(dragScroll);}if(d.moved){event.preventDefault();d.ghost.style.left=event.clientX+12+'px';d.ghost.style.top=event.clientY-15+'px';}},{passive:false});
 function dropDie(b,id,x,y){const candidates=[...document.querySelectorAll('.player-board [data-instance]')].map(el=>{const rect=el.getBoundingClientRect(),dx=Math.max(rect.left-x,0,x-rect.right),dy=Math.max(rect.top-y,0,y-rect.bottom);return {el,rect,distance:Math.hypot(dx,dy)};}).filter(c=>c.distance<=26).sort((a,b)=>a.distance-b.distance);
  const candidate=candidates[0];if(!candidate)return false;const {el,rect}=candidate;return E.placeDie(b,id,el.dataset.instance,x<rect.left+rect.width/2?'L':'R');
 }
 document.addEventListener('pointerup',event=>{const d=ui.drag;ui.drag=null;if(!d)return;d.ghost?.remove();if(!d.moved)return;suppressClick=true;setTimeout(()=>suppressClick=false,80);const target=document.elementFromPoint(event.clientX,event.clientY),b=state.run?.battle;if(!b)return;
  if(d.type==='die'){if(dropDie(b,d.id,event.clientX,event.clientY)){ui.die=null;changed();}else toast('카드의 좌우 영역에 놓으세요. 오른쪽은 같은 눈만 가능합니다.');}
  else if(b.phase==='p_attack'){const card=target?.closest('[data-side="e"]');if(card)attack(d.id,card.dataset.id);}
  else{const cell=target?.closest('[data-field-side="p"]');if(cell&&E.moveCard(b,d.id,+cell.dataset.position)){ui.selected=d.id;changed();}}
 });
 document.addEventListener('pointercancel',()=>{ui.drag?.ghost?.remove();ui.drag=null;});
 window.addEventListener('scroll',updateAction,{passive:true});
 window.addEventListener('pagehide',save);
 // Small, explicit interface for regression tests; no automatic player placement in the UI.
 window.ElementalDice={version:'1.0.0',getState:()=>E.copy(state),engine:E,setTestMode:value=>{ui.fast=!!value;},validate:()=>state.run?.battle?E.validate(state.run.battle):[]};
 save();render();if(ui.view==='battle'&&!checkEnd())drive();
})();
